# volumes:
#   db_data:
version: '3.8'
networks:
  app_network:
    driver: bridge
    external: true
    name: app_network
services:
#   Laravel Backend
  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/var/www/app/backend
  #     - ./frontend:/var/www/html/frontend
  #     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf
  #   depends_on:
  #     - frontend
  #   networks:
  #     - app_network

  # backend:
  #   container_name: backend_svc
  #   image: laravelgis-php:latest
  #   restart: unless-stopped
  #   build:
  #     context: ./backend/docker/php
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./backend:/var/www/app/backend
  #   networks:
  #     - app_network

  backend:
    image: nginx:latest
    container_name: laravel-svc
    ports:
    - "8000:8000"
    volumes:
    - ./backend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./backend:/var/www/app
    networks:
      - app_network

  php:
    build:
        context: ./backend/docker/php
        dockerfile: Dockerfile
    ports:
         - "9000:9000"
    image: laravelgis-php:latest
    container_name: backend-svc
    volumes:
        - ./backend:/var/www/app
    networks:
        - app_network


  # Vue Frontend with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-app
    restart: unless-stopped
    ports:
      - "8778:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/var/www/html/frontend
    networks:
      - app_network

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'ticket_db'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      - app_network

# volumes:
#   db_data:
