version: '3.8'

services:
  # Laravel Backend
  laravel:
        image: nginx:latest
        container_name: laravel-svc
        ports:
        - "8000:8000"
        volumes:
        - ./backend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        - ./backend:/var/www/app

  php:
      build:
          context: ./backend/docker/php
          dockerfile: Dockerfile
      ports:
          - "9000:9000"
      image: laravelgis-php:latest
      container_name: backend-svc
      volumes:
          - ./backend:/var/www/app


  # Vue Frontend with Nginx
  vue:
    build:
      context: ./frontend
    container_name: vue-app
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - laravel
    volumes:
      - ./frontend:/app

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'ticket_db'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - /usr/local/var/mysql:/var/lib/mysql

networks:
  app-network:
    driver: bridge

# volumes:
#   db_data:
